[package]
name = "axum_demo"
version = "0.4.0"
edition = "2021"
authors = ["Yusong Lai <yusong.lai@icloud.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[profile.release]
lto = "thin"
panic = "abort"
strip = "symbols"

[features]
default = ["mimalloc"]

[dependencies]
# heap memory allocator
mimalloc = { version = "0.1.39", default-features = false, optional = true }
# web serivce
axum = "0.7.1"
tower = { version = "0.4.13", features = ["timeout", "buffer"] }
# error handling
anyhow = "1.0.75"
# serialization
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
# async
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
# log
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
# utilities
uuid = { version = "1.6.1", features = ["v4", "serde"] }
ahash = { version = "0.8.6", features = ["serde"] }
once_cell = "1.18.0"
# database
mongodb = "2.7.1"
