[package]
name = "axum_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[profile.release]
lto = "thin"
panic = "abort"
codegen-units = 1

[dependencies]
# heap memory allocator
mimalloc = { version = "0.1.36", default-features = false }
# web serivce
axum = "0.6.10"
tower = { version = "0.4.13", features = ["timeout", "buffer"] }
# error handling
anyhow = "1.0.69"
# serialization
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
# async
tokio = { version = "1.25", features = ["full"] }
# log
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
# utilities
uuid = { version = "1.3.0", features = ["v4", "serde"] }
ahash = { version = "0.8.3", features = ["serde"] }
