[package]
name = "axum_demo"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[profile.release]
lto = "thin"
panic = "abort"
codegen-units = 1

[dependencies]
# heap memory allocator
mimalloc = { version = "0.1.37", default-features = false }
# web serivce
axum = "0.6.18"
tower = { version = "0.4.13", features = ["timeout", "buffer"] }
# error handling
anyhow = "1.0.71"
# serialization
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
# async
tokio = { version = "1.28", features = ["full"] }
futures = "0.3.28"
# log
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
# utilities
uuid = { version = "1.3.2", features = ["v4", "serde"] }
ahash = { version = "0.8.3", features = ["serde"] }
once_cell = "1.17.1"
# database
mongodb = "2.5.0"
