# Use this file for production.

services:
  axum-demo:
    init: true
    image: whisperpine/axum-demo:latest
    pull_policy: always
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: axum-demo
      TIMEOUT_SECS: 0.8
      # RUST_LOG: axum_demo=debug
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    pull_policy: always
    volumes:
      - mongo-data-db:/data/db
      - mongo-config-db:/data/configdb

volumes:
  mongo-data-db: {}
  mongo-config-db: {}
