# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# Use this file for local test.

services:
  axum-demo:
    init: true
    build:
      context: .
      target: final
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: index.html
    environment:
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: axum-demo
      TIMEOUT_SECS: 0.3
      RUST_LOG: axum_demo=debug
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data-db:/data/db
      - mongo-config-db:/data/configdb

volumes:
  mongo-data-db: {}
  mongo-config-db: {}
