# ----------------------------------------
# build from rust, start from debian
# ----------------------------------------

FROM rust AS builder
WORKDIR /project/
COPY .cargo/config.toml ./.cargo/
COPY Cargo.toml .
RUN cargo fetch
COPY . .
RUN cargo build --offline --release

FROM debian:12-slim
COPY --from=builder /project/target/release/axum_demo /app/
EXPOSE 3000
CMD [ "/app/axum_demo" ]
