# Use this file for local test.

services:
  axum-demo:
    image: axum-demo
    pull_policy: never
    container_name: axum-demo
    hostname: axum-demo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=axum-demo
    ports:
      - 3000:3000

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data-db:/data/db
      - mongo-config-db:/data/configdb

volumes:
  mongo-data-db: {}
  mongo-config-db: {}
