# Use this file for production.

services:
  axum-demo:
    image: whisperpine/axum-demo:latest
    pull_policy: always
    container_name: axum-demo
    hostname: axum-demo
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=axum-demo
    ports:
      - 3000:3000

  mongo:
    image: mongo:6.0
    pull_policy: always
    container_name: axum-demo-mongo
    hostname: axum-demo-mongo
    volumes:
      - mongo-data-db:/data/db
      - mongo-config-db:/data/configdb

volumes:
  mongo-data-db: {}
  mongo-config-db: {}
